### ISSUE TITLE
Issue when clearing and refilling an ofxGuiMatrix

### ISSUE THREAD

**Issue by gorkacortazar** [frauzufall/ofxGuiExtended#14]
After filling the matrix the first time everything works correctly
![screen shot 2015-07-17 at 14 54 54](https://cloud.githubusercontent.com/assets/608719/8747504/0a26a78a-2c94-11e5-9e37-c3b056e884c3.png)

But after using the method matrix.clear() and refill it with the same or different content the colours look inverted (this is after filling everything as false)
![screen shot 2015-07-17 at 14 55 12](https://cloud.githubusercontent.com/assets/608719/8747519/33ea6660-2c94-11e5-9453-3bae9936a6da.png)

I will take a look over the weekend in more detail.

**Comment by frauzufall** [comment]
should be fixed. please test and close it if everything is fine!
