### ISSUE TITLE
ofxRotarySlider endless rotation

### ISSUE THREAD

**Issue by thomasgeissl** [frauzufall/ofxGuiExtended#15]
ofxRotarySlider should stop at the minimum and maximum position, unless it is set to be endless. 
I will have a look at this tomorrow. Is it useful to have an option for endlos rotation?

**Comment by frauzufall** [comment]
You mean, if I drag the mouse left around the slider and further, it should stop at 0? That would be nice. No option. It's not like this yet because I adapted ofxUIRotarySlider and there it also just goes from min to max if you drag further.

**Comment by thomasgeissl** [comment]
Yes, that is what I mean. 
I will try to do this, but (without having a look at the code) it seems to be a bit tricky.

**Comment by frauzufall** [comment]
Yes, I can't think of any super simple solution either right now.

**Comment by frauzufall** [comment]
This should work..
Always save the last dragging point and check if the line between the last and the current dragging point crosses a vertical line down from the circle center to the bottom of the screen. If it does, check which x value is bigger, set the value accordingly to min and max value and do not change the last dragging point.
![rotarslider](https://cloud.githubusercontent.com/assets/708121/8850399/1039daf8-3148-11e5-9934-c262263349f1.png)

I can also implement it, just don't know when exactly.

**Comment by thomasgeissl** [comment]
At this point I would also like to discuss the dragging itself. 
In Ableton Live you just drag the mouse up or down to turn a knob's left or right. Same counts for pd, JUCE library, MAX. It is easier and faster than doing an actual circle with the mouse and should be the default in my opinion.

**Comment by frauzufall** [comment]
Sure. That also simplifies the implementation a lot ;) Whats the convention on how far you have to go up or down to get the min or max value?

**Comment by thomasgeissl** [comment]
I would make that depend on the size of the slider. It looks like this is the way how it is done in pd.
Ableton Live and MAX also disable the cursor while dragging. 
This can be done in oF with 

``` c++
ofHideCursor();
ofShowCursor();
```

**Comment by frauzufall** [comment]
I changed it, it uses the height of the slider as reference for the value. Have a look.
Whats the purpose of disabling the cursor? Because you cannot set the value of the slider by clicking on it? Would the cursor then also disappear while hovering the slider?

**Comment by thomasgeissl** [comment]
I will have a look tonight.

The cursor does not disappear while hovering, just while dragging. 
I guess the purpose is that users could get confused. But pd on the other hand does not hide the cursor. 
I never got confused.

**Comment by thomasgeissl** [comment]
It immediately jumps to a new position when pressing the mouse. 

We should save that value (_mousePressedY) and shift the dragging area. 
So that _mousePressedY gets mapped to the currentValue.

I made a little drawing. I try to get this done this weekend.
Lets say the current value is 75%. And x is the starting point (_mousePressedY). 
The block on the left side represents the knob. The block on the right side the dragging area.

![screen shot 2015-07-24 at 19 25 20](https://cloud.githubusercontent.com/assets/3796674/8880575/152d27a2-323a-11e5-84b1-e6fbe9241af8.png)

I hope that makes sense.

**Comment by frauzufall** [comment]
It made sense, check it out!

**Comment by thomasgeissl** [comment]
wow, it works perfectly.
I thought about the reason for hiding the cursor. In Live the cursor gets reseted when the value is set. So it is at the same position as before. And it would be strange if the cursor jumps.
I have no idea how the cursor can be set in oF.
http://forum.openframeworks.cc/t/set-cursor-position/735/9
But I do not think it is important to implement this.

**Comment by frauzufall** [comment]
Perhaps we just show the cursor again. I don't really get the advantage of it.

**Comment by thomasgeissl** [comment]
If we cant reset the cursor position, I would show it again.
