### ISSUE TITLE
Crash in OF 0.8.4 VS2012  with solution 

### ISSUE THREAD

**Issue by chemabc** [frauzufall/ofxGuiExtended#17]
Hi, 

Great addon! thansk for it. 
I have being testing it in of 0.8.4 for VS2012. I had to change some small details in the official ofxGui cause some changes from of 0.9.0 were not applied yet. I forked your project ofxGuiExtended and also ofxGui create a 0.8.4 branch just in case anyone needs it. 

The important thing: I faced a crash when using ofxGuiGroupExtended. I found that "parent" was not initialized so there was a infinite loop. I added the initlialization and works like a charm. 

I'm gonnna make just now the pull request.

**Comment by frauzufall** [comment]
I removed the initialization line again because it is now part of ofxBaseGui. Please update your OF git in order for it to work!

**Comment by chemabc** [comment]
Perfect! I'll do that. 
Thanks!
