### ISSUE TITLE
ofxGuiMatrix not possible to unset all toggles

### ISSUE THREAD

**Issue by thomasgeissl** [frauzufall/ofxGuiExtended#22]
I saw you and Arturo are working on the gui addon and I am looking forward to give it a try.

One thing i noticed:
It is not possible to unset all toggles in a gui matrix if it is set to exclusive.

I just wanted to file this issue in case you are refactoring the gui matrix you could have a look. But I can also do this, once you are done.

**Comment by frauzufall** [comment]
Mh, this is intentional. I always need one (if none was selected at the beginning then the first) toggle to be selected. Not sure what the convention is - do you know how other frameworks handle this? Or if there is an option to choose? Will have a look at Qt later.

**Comment by thomasgeissl** [comment]
Not sure about other frameworks. You are probably right, it makes sense to require one selected toggle.
I was using it as an input selector {beat detector, metronom, osc}. But I can add a none item. 
We could keep the current solution the default and add an option to the matrix/toggle group.
I will check other frameworks.

**Comment by thomasgeissl** [comment]
Other frameworks require also one selected toggle. 
The only exception is at the beginning. There are situations you don't want a default selection. Here are some examples: http://ux.stackexchange.com/a/76182

I think we can close this.
