### ISSUE TITLE
ofxTabbedPages background color

### ISSUE THREAD

**Issue by nanu-c** [frauzufall/ofxGuiExtended#25]
How can I set the ofxTabbedPages background color for the tabs?

```
ofxGuiSetFillColor(ofColor(0xff,0x4f,0x20,100));
ofxGuiSetBackgroundColor(ofColor(0xff,0xa5,0x8d,100));
Page.setDefaultBackgroundColor(ofColor(0xff,0xa5,0x8d,100));
Page.setDefaultFillColor(ofColor(0xff,0xa5,0x8d,100));
tabbedPages.setDefaultBackgroundColor(ofColor(0xff,0xa5,0x8d,100));
```

This one aren't working.

**Comment by frauzufall** [comment]
Sorry I did not reply - if anyone is still interested in that, in the new version there is an example showing colored tabs: https://github.com/frauzufall/ofxGuiExtended/tree/master/exampleLayout
