### ISSUE TITLE
merge gui extensions

### ISSUE THREAD

**Issue by martialgallorini** [frauzufall/ofxGuiExtended#26]
hello,

is there a release date for the merge of this addon into openFrameworks core ofxGui ?

thanks a lot

**Comment by frauzufall** [comment]
There is still some work to be done but this is the PR https://github.com/openframeworks/openFrameworks/pull/4306 It will hopefully be a part of OF v0.10.

**Comment by martialgallorini** [comment]
ok. thanks for the update.
thanks for this great effort in building useful gui extensions.
all the best

**Comment by frauzufall** [comment]
Closing this since it will stay an external addon.
