### ISSUE TITLE
No member named 'getTogglesExclusive' in 'ofxGuiGroup'

### ISSUE THREAD

**Issue by interior-night** [frauzufall/ofxGuiExtended#29]
Thanks for a brilliant addon!

I'm receiving two errors though with the new version:

ofxGuiToggle.cpp:284:15: No member named 'getTogglesExclusive' in 'ofxGuiGroup'
ofxGuiToggle.cpp:295:13: No member named 'deactivateAllOtherToggles' in 'ofxGuiGroup'

But ofxGuiToggle.h does define both of those...

Not sure what I've done wrong.

**Comment by frauzufall** [comment]
Hey, thanks for testing it!
Perhaps you compiled the old version before, did you clean the example?

**Comment by interior-night** [comment]
Pretty sure I'm using the latest. Just tried with a clean example and all is working well aside from a few override warnings. So the problem must be linked to my code, I suppose. Any clues why I might get that warning?

**Comment by interior-night** [comment]
I suppose I should mention I'm trying to use ofxGuiExtended with ofxAppUtils and a couple of other addons.

**Comment by frauzufall** [comment]
I meant if you cleaned your project, I don't know how this is called on Windows or Mac but something like "clean" or "rebuild" instead of a normal "build". This deletes all old binaries and takes care everything is compiled from scratch. Did you try this?

Can you also please post the override warnings?

**Comment by interior-night** [comment]
All good now. Had some header search paths missing after the update.

**Comment by interior-night** [comment]
Override issues are:

in ofxGuiGroup.h:

```
virtual void generateDraw();
virtual void render();
virtual void _setConfig(const ofJson & config);
```

in ofxGuiButton.h:

```
virtual void generateDraw();
bool setValue(float mx, float my, bool bCheck);
```

in ofxGuiGraphic.h:

```
virtual ofAbstractParameter & getParameter();
bool setValue(float mx, float my, bool bCheckBounds){ return false;};
virtual void render();
virtual void generateDraw();
```

in ofxGuiInputField.h:

```
ofAbstractParameter & getParameter();
virtual void render();
bool setValue(float mx, float my, bool bCheck);
virtual void generateDraw();

```

in ofxGuiLabel.h:

```
virtual void saveTo(ofBaseSerializer& serializer){}
virtual void loadFrom(ofBaseSerializer& serializer){}
ofAbstractParameter & getParameter();
```

in ofxGuiSlider.h:

`ofAbstractParameter & getParameter();`

in ofxGuiToggle.h:

```
virtual ofAbstractParameter & getParameter();
virtual bool setValue(float mx, float my, bool bCheck);
virtual void generateDraw();
```

**Comment by frauzufall** [comment]
Happy that it works now! 

What about the header links, is there a wrong path somewhere in the addon? I don't really know how to link them the best way with the folders in the src directory but I needed some structure. Which system are you using?

I updated the code, the overrides should be gone. Please tell me if something still comes up. Thank you!

**Comment by interior-night** [comment]
Override warnings are gone. No, the header search path issue was entirely my fault so I don't think you need to change anything there. Working great so far!
