### ISSUE TITLE
Compilation problem OSX

### ISSUE THREAD

**Issue by gorkacortazar** [frauzufall/ofxGuiExtended#3]
The destructor of the rotary slider throws a compilation error in OSX

```
/Volumes/DataHD/Projects/ofx_090/addons/ofxGuiExtended/src/ofxRotarySlider.cpp:14:23: Expected the class name after '~' to name a destructor
```

**Comment by frauzufall** [comment]
Thank you for testing! Can you pull and try again? I read about it and it should be ok now, but I can't test it.

**Comment by gorkacortazar** [comment]
It compiles without problems now.

One minor detail, is that the projectGenerator in osx replaces the '-' character in the example name with '_', making more difficult creating the example projects.

**Comment by frauzufall** [comment]
Alright, I renamed them, thank you :)
