### ISSUE TITLE
Custom Fonts?

### ISSUE THREAD

**Issue by interior-night** [frauzufall/ofxGuiExtended#30]
What are our options regarding customising fonts? Can this be done through the JSON too?

I've really been liking the flexibility of the theming so far!

**Comment by frauzufall** [comment]
Check out the updated [theme example](https://github.com/frauzufall/ofxGuiExtended/tree/master/exampleThemes) :) 
Small bugs: If you change the font size, the minimal sizes of the controls are not calculated correctly (the font will overlap). Also you can't change the font size if you don't set a font family.
Give it a try!

**Comment by frauzufall** [comment]
Argh I just realized that the files in bin/data were missing for most of the examples so they did not really work as expected. I uploaded them all now.

**Comment by interior-night** [comment]
Fantastic. Cheers!
