### ISSUE TITLE
Black background on Panel and Group header text.

### ISSUE THREAD

**Issue by interior-night** [frauzufall/ofxGuiExtended#31]
The background behind Panel and Group header text remains black when I make the header semi-transparent. But the text background looks as expected on sliders, value plotters, buttons and toggles. Any ideas?

**Comment by frauzufall** [comment]
What exactly do you mean? The header is laying on top of the panel/group background, so if the panel or group isn't transparent, you also won't see the background through the header. I am not happy with the implementation of the header, but I got no other idea right now. If you want the content beneath the header have a different padding / background, you can create a group with transparent background and your desired header config and add a group with hidden header where you set the group background. I did this in the second example of [ofxSortableList](https://github.com/frauzufall/ofxSortableList), have a look at the screenshot there.

**Comment by interior-night** [comment]
It must be something in my json theme that's causing the problem. Here is what I mean:

![screen shot 2016-05-12 at 00 39 07](https://cloud.githubusercontent.com/assets/652507/15185384/3d6a064e-17dc-11e6-8a5c-25357f8fe9f9.png)

and I just tried with a custom font and now this is what happens:

![screen shot 2016-05-12 at 00 52 38](https://cloud.githubusercontent.com/assets/652507/15185402/5012b1d8-17dc-11e6-936b-7d151601d20e.png)

By the way, my custom font looks a bit fuzzy on some components.

Here's my json theme:

```
{
    "bleurgh": {
        "base": {
            "background-color": "rgba(0,0,0,0.3)",
            "fill-color": "rgba(220,80,50,1)",
            "border-width": 0,
            "padding": 5,
            "border-color": "rgba(0,0,0,0.3)",
            "margin": 5,
            "text-color": "rgba(255,255,255,0.8)",
            "text-padding": 5,
            "font-size": 18,
            "width": 350,
            "font-family": "GUI/fonts/NewMediaFett.ttf",
            "font-size": 9
        },

        "group": {
            "background-color": "rgba(0,0,0,0.2)",
            "border-color": "rgba(0,0,0,0.6)",
            "padding": 0,
            "margin": 1,
            "border-width": 1
        },

        "group-header": {
            "height": 40,
            "margin-right": 0,
            "background-color": "rgba(0,0,0,0.2)",
            "text-color": "#ffffff",
            "border-color": "rgba(0,0,0,0.6)",
            "border-width": 1
        },

        "panel": {
          "width": 350,
          "direction": "vertical",
          "show-header": true,
          "background-color": "rgba(0,0,0,0.3)"
        },

        "slider": {
          "fill-color": "rgba(220,80,50,1)",
          "precision": 3,
          "border-width": 1,
          "border-color": "rgba(0,0,0,0.5)"
        },

        "toggle": {
          "height": 40,
          "border-color": "rgba(220,80,50,1)",
          "background-color": "rgba(220,80,50,0.1)",
          "fill-color": "rgba(220,80,50,0.7)",
          "border-width": 1,
          "type": "fullsize"
        },

        "button": {
          "fill-color": "rgba(220,80,50,1)"
        },

        "label": {
          "text-color": "rgba(220,80,50,1)",
          "background-color": "rgba(0,0,0,0)"
        },

        "graphics": {
          "background-color": "rgba(0,0,0,0)"
        },

        "value-plotter": {
          "fill-color": "rgba(220,80,50,1)",
          "height": 40,
          "precision": 3,
          "border-width": 1,
          "border-color": "rgba(0,0,0,0.4)"
        },

        "function-plotter": {
          "fill-color": "rgba(220,80,50,1)",
          "precision": 3,
          "border-width": 1,
          "border-color": "rgba(0,0,0,0.4)"
        },

        "tabs": {
          "padding": 20
        }


    }
}
```

and for example, in my ofApp.cpp: 

```
    pitchGroup = audioAnalyzerPanel->addGroup("PITCH", ofJson({{"flex-direction", "row"}, {"flex-wrap", "wrap"}}));
    pitchGroup->add(pitchToggleVal, ofJson({{"type", "radio"}, {"show-name", false}, {"width", "10%"}}));
    pitchGroup->add<ofxGuiValuePlotter>(pitchPlotterVal, ofJson({{"width", "90%"}}));
    pitchGroup->add(pitchConfSliderVal);
```

Any ideas what I may be doing wrong?

**Comment by interior-night** [comment]
Also, you can see in the screenshots that the headers have got a small margin on the right which I don't want but I'm not sure how it got there.

**Comment by frauzufall** [comment]
Thanks for all the details! I got the first one figured out (see commit) but the header margin thing is strange. Found quite some new layout issues, this shit is tricky. I will try my best.

Btw I really like the theme :)

**Comment by frauzufall** [comment]
And I sadly have no idea what the reason for the fuzzy font is. I had this too before, right now it looks nice, no clue..

**Comment by interior-night** [comment]
Wish i had better skills... I'd gladly help out. But I'm learning fast - have only started with c++/openFrameworks in the last fortnight. GIve me another couple of weeks and I can probably start to contribute some code. In the meantime, I'll just create more "issues" for you, if you don't mind!

And feel free to use my theme of course.

**Comment by frauzufall** [comment]
It's already really helpful to get your issues, you are the first one actively trying out this addon and giving me feedback so thank you very much! I want to use this addon for my projects and I really want it to be reliable, stable, fast and flexible, but since it's pretty complex it's hard to test everything by myself. 

Is the header margin thing still a problem? If yes, please report a separate issue, also for the font issue.

**Comment by interior-night** [comment]
Cool. I'll open some new issues but will investigate a bit more first to avoid wasting your time.

**Comment by frauzufall** [comment]
Don't spend too much time with the layout right now, I found some bugs myself and I am rewriting it once again. Let's hope I get it right this time.
