### ISSUE TITLE
Group header margin problems when set in pixels.

### ISSUE THREAD

**Issue by interior-night** [frauzufall/ofxGuiExtended#32]
Group headers appear to be too short when their width is set in pixels and the base header has left/right margins.

For example, if you set a width of 250 and a margin of 10 for the base , then you need to set the group-header to be set to "100%" or, un-intuitively, 270.

**Comment by frauzufall** [comment]
Ahh now I know the problem. 

"base" does not stand for the root panel, it sets rules for all elements. It's the base class. With your theme you give the sliders a width of 250 and margin 10 as well, that's why the panel grows to 270.
 I understand that the name is confusing. What would be better,  "*" or "element"?

**Comment by frauzufall** [comment]
If you want the main panel to have a specific size, you have to set that via inline json when you create it.

**Comment by frauzufall** [comment]
Also, please update, the standard layout should be better now.

**Comment by interior-night** [comment]
Yeah. I realised too late that I was the one not being intuitive. But maybe renaming "base" to "default" or "element" may make things clearer for unattentive people like me. I was also confused by the fact that setting a width on a panel - but not on the base - didn't appear to have an effect on that panel's width but i've quite possibly done something wrong there too! Have just updated in any case and will check things out again.

**Comment by interior-night** [comment]
"Base" could be "all-elements" if you want to make things fool-proof?

**Comment by interior-night** [comment]
Just checked... font issue is fixed! even before i got around to creating an issue. Great job!
