### ISSUE TITLE
Group margins set incorrectly

### ISSUE THREAD

**Issue by interior-night** [frauzufall/ofxGuiExtended#33]
With the latest update I've noticed the following happens to collapsed groups:

No group collapsed, all good: 
![screen shot 2016-05-13 at 09 34 57](https://cloud.githubusercontent.com/assets/652507/15233754/94b095c2-18ee-11e6-964c-f54a74551f29.png)

Pitch group collapsed, wonky margins for other groups:

![screen shot 2016-05-13 at 09 35 09](https://cloud.githubusercontent.com/assets/652507/15233770/b7f60bde-18ee-11e6-9876-275cf87bceff.png)

**Comment by frauzufall** [comment]
I guess this was also created with flexbox layout? please test again and close if it works or post screenshots / code snippets to help me fix it. Thank you!

**Comment by interior-night** [comment]
Seems to be working now. Cheers.
