### ISSUE TITLE
buggy flexbox layout

### ISSUE THREAD

**Issue by frauzufall** [frauzufall/ofxGuiExtended#35]
the flexbox layout is currently not correctly functioning. i am working on it.

**Comment by interior-night** [comment]
Cool. Yeah, some things have gone funny but I'm really liking the way my interface is starting to take shape. Very flexible GUI.

**Comment by frauzufall** [comment]
Glad that you like it! Can you test if your issues are gone?

**Comment by interior-night** [comment]
Yep. All big issues are gone. Some things are still a bit confusing but I think i just need to tweak my theme some more. I'll give you more feedback tomorrow. I'm off to sleep now...

**Comment by interior-night** [comment]
Still having a couple of issues but i might have done something wrong.
Here's where I'm at so far (unfinished!):

![screen shot 2016-05-16 at 00 17 06](https://cloud.githubusercontent.com/assets/652507/15274697/6bc33c7c-1afc-11e6-8acc-cb3b8a1e46bb.png)

One problem, for example, is the spacing between the toggle at the top left and the two faders next to it. The toggle is set to 10% width and the faders to 45% each. They're in a group that's 100% wide in a panel 300px wide. I guess i need to take margins and whatnot into account? Or is it something else? I'll play with alignment options some more in case that's the solution.

**Comment by frauzufall** [comment]
That's a bug, I'll have a look at it, thanks for the details!

**Comment by frauzufall** [comment]
can you update and check again?

btw margins and paddings are subtracted from the percental size so you don't need to take them into account. this needs more documentation.

**Comment by interior-night** [comment]
Working! Cheers!

![screen shot 2016-05-16 at 11 21 47](https://cloud.githubusercontent.com/assets/652507/15278239/0717643a-1b59-11e6-9f91-2be9b56b81f7.jpg)

**Comment by frauzufall** [comment]
Cool. Can I use this picture (with reference) if I ever have a page where I show examples of ofxGuiExtended in action?

**Comment by interior-night** [comment]
Of course!
