### ISSUE TITLE
Doesn't compile in Windows - VS2015

### ISSUE THREAD

**Issue by gorkacortazar** [frauzufall/ofxGuiExtended#4]
I was trying the addon in VS2015 (of 0.9 is being optimized for that upcoming version) and there are several instances of this error

```
Error   C2065   'uint': undeclared identifier   example_elements_options    C:\Users\drakko\Documents\ofx_090\addons\ofxGuiExtended\src\ofxTabbedPages.cpp  233
```

It happens in 32 and 64 bits compilations. Changing the type of int solves the compiler error.

**Comment by frauzufall** [comment]
Should work now?

**Comment by gorkacortazar** [comment]
Yep it compiles correctly now.
