### ISSUE TITLE
Panel height not minimizing after group->minimize()

### ISSUE THREAD

**Issue by interior-night** [frauzufall/ofxGuiExtended#41]
I've noticed that if I minimize a group's contents, the panel's background keeps the same full-height as the minimized group use to have, pushing any subsequent elements down. It might be easier to illustrate what I mean with an image sequence:

![screen shot 2016-05-25 at 12 18 56](https://cloud.githubusercontent.com/assets/652507/15526141/ed429b4e-2272-11e6-93bd-ad140bd4f618.png)
i open the effects panel
![screen shot 2016-05-25 at 12 16 04](https://cloud.githubusercontent.com/assets/652507/15526144/f4d1ea90-2272-11e6-8d26-9fb4a780d5d9.png)
I open the transform group
![screen shot 2016-05-25 at 12 16 19](https://cloud.githubusercontent.com/assets/652507/15526147/f866317a-2272-11e6-9b43-eb23c40dfc4a.png)
and close it... but the panel height is not minimized
![screen shot 2016-05-25 at 12 17 15](https://cloud.githubusercontent.com/assets/652507/15526159/100339f4-2273-11e6-8e9d-5f68177509a3.png)
and if i open the post processing group
![screen shot 2016-05-25 at 12 17 25](https://cloud.githubusercontent.com/assets/652507/15526161/1437e56a-2273-11e6-8860-40d26b6854d5.png)
and then minimize it... the transformer group is no longer visible (pushed off screen)
![screen shot 2016-05-25 at 12 17 55](https://cloud.githubusercontent.com/assets/652507/15526164/19aafc62-2273-11e6-896d-5ccf75a8f559.png)
But it can be recovered by minimizing the effects panel...
![screen shot 2016-05-25 at 12 18 07](https://cloud.githubusercontent.com/assets/652507/15526166/1d3d415a-2273-11e6-9cea-9a8008118a3b.png)
and then reopening it...
![screen shot 2016-05-25 at 12 18 13](https://cloud.githubusercontent.com/assets/652507/15526177/2e74743e-2273-11e6-86da-860621172a66.png)

**Comment by frauzufall** [comment]
Yes that shouldn't happen, I could reproduce it with your deBug code  and I will have a look at it.

**Comment by frauzufall** [comment]
It's got to do with your group theme. At least it works (the app that you gave me access to) when I change this line: 

```
ofJson groupTheme = {{"flex-direction", "row"}, {"flex-wrap", "wrap"}, {"width", 320}, {"align-content", "space-between"}};
```

to

```
ofJson groupTheme = {{"width", 320}, {"align-content", "space-between"}};
```

Check if this line is still the same in your code. You are not trying to create a row layout there, are you?

**Comment by interior-night** [comment]
Yep. Working now. Cheers!

**Comment by interior-night** [comment]
Actually... removing `{"flex-direction", "row"}, {"flex-wrap", "wrap"}` fixes the vertical spacing issue but causes the group to once again no longer display the 10% width toggle on the same row as the 45% width sliders. I'm sure it's something to do with my theme but flexbox is still a bit confusing for me! I've uploaded a cleaned-up version of my deBug code if you have the time to peak inside.

**Comment by interior-night** [comment]
And another thing that confuses me is that `"show-name": false` doesn't seem to work for me in the json file but if i do `"show-name", false` as inline json it does work.

**Comment by frauzufall** [comment]
Yes, I had some similar issues. Will work on it. I also understand now why you used `{"flex-direction", "row"}, {"flex-wrap", "wrap"}` and it should actually do what you expected it to do, I will try to fix that. 

Can you tell me for which class type `"show-name"` did not work from the theme?

**Comment by interior-night** [comment]
Cool. Show-name hadn't worked for toggles but I think I also tried on sliders without success.

**Comment by frauzufall** [comment]
Update.

**Comment by interior-night** [comment]
All appears to be working now! Cheers! Only two issues I'm noticing... If I show the headers (Settings/Panels/Unlock Panels in the debug app) the panel shifts to the right of the header. I'm guessing this has to do with the `"flex-direction": "row"` on the group but will investigate. Also, I'm getting 3 warnings in the console that I can't figure out...

```
[warning] Adding another parameter with same name '' to group 'Camera'
[warning] Adding another parameter with same name '' to group 'menubar'
[warning] Adding another parameter with same name '' to group 'Scenes Menu'
```

**Comment by frauzufall** [comment]
The warnings are due to the fact that you initialize the parameters in line 114 after creating the gui. That means that in the moment you add them to the panel, they have no name yet and will therefore throw this warning.
