### ISSUE TITLE
Windows compile error

### ISSUE THREAD

**Issue by brinoausrino** [frauzufall/ofxGuiExtended#43]
In order to compile ofxGuiExtended on Visual Studio the following things need to be edited.

"ABSOLUTE" defines some kind of system variable, so the value needs to be changed.
`Types.h -> LayoutPosition` (I changed `ABSOLUTE` to `ABSOLUTE_`)

`Element.cpp ->``removeLayout()` does not return any Value

**Comment by frauzufall** [comment]
Thanks for opening this issue and sorry for the late reply. Element::removeLayout() ist not yet implemented, but it is returning a nullptr for now. Can you give me more details about this ABSOLUTE variable? I can't really find a source for this but I would like to know the reason before renaming it.
