### ISSUE TITLE
VS2015. Empty Project. Doesn't compile

### ISSUE THREAD

**Issue by leefeel** [frauzufall/ofxGuiExtended#45]
In Windows 10. VS2015. 

Just updated openframeworks from the master branch.

I just downloaded ofxGuiExtended. And added it to an empty project through the projectGenerator. 

I tried to compile, without adding any other addon on the project, and I get 1993 compile error, among them:

C2440   '<function-style-cast>': cannot convert from 'initializer list' to 'DOM::ofPoint'   extendedGUIexamble  C:\OpenFrameworks\openFrameworks-6bdacbc04eccad400896cb703a2ded3234420671\addons\ofxGuiExtended\src\DOM\Element.cpp 547 

....

C2988   unrecognizable template declaration/definition (compiling source file ......\addons\ofxGuiExtended\src\ofxGuiExtended.cpp)    extendedGUIexamble  c:\openframeworks\openframeworks-6bdacbc04eccad400896cb703a2ded3234420671\addons\ofxguiextended\src\containers\ofxGuiContainer.h    170

**Comment by frauzufall** [comment]
Thanks for opening this issue, I have not been updating my OF branch because of the vector discussions but it works fine for me now with the fixes I uploaded. Please check it out and reopen if you still have problems.
