### ISSUE TITLE
Problem building examples on OS X

### ISSUE THREAD

**Issue by narner** [frauzufall/ofxGuiExtended#47]
Hey there, 

I'm having an issue building the example projects on OS X (El Capitan 10.11.4). As you specified in the README, I'm on commit [c9cd3e9](https://github.com/openframeworks/openFrameworks/commits/c9cd3e9) of OpenFrameworks:

![screen shot 2016-09-05 at 11 25 56 am](https://cloud.githubusercontent.com/assets/2131591/18252245/91015caa-735b-11e6-831b-0fc4feabc895.png)

However, I'm still experiencing build issues regarding `ofJson.h` not being found:

![screen shot 2016-09-05 at 11 26 25 am](https://cloud.githubusercontent.com/assets/2131591/18252257/9fed61b4-735b-11e6-9f80-fa6798c46a61.png)

**Comment by avilleret** [comment]
you might try to build against master
I was not able to build against https://github.com/openframeworks/openFrameworks/commit/c9cd3e912691d5286c3b6c84d6dd83de055e89d0 but https://github.com/openframeworks/openFrameworks/commit/19ec2688df9eecd818e333bef4753c302058de17 works fine here (on Ubuntu 16.04.1)

**Comment by narner** [comment]
@avilleret Gotchya; I tried setting OF to that [commit](openframeworks/openFrameworks@19ec268), but now I'm having a problem where the Project Generator doesn't see the ofxGuiExtended addon, even though it's in the correct folder:

![screen shot 2016-09-19 at 1 23 14 pm](https://cloud.githubusercontent.com/assets/2131591/18641862/683230bc-7e6c-11e6-84c2-245ca9f196be.png)

**Comment by narner** [comment]
Never mind; it's working now (the problem I had in the problem above was because the Project Generator was pointing to an OF folder that was a sub-project of a different repo somewhere else...)

**Comment by narner** [comment]
@avilleret, I realized that for other parts of my app, I'd need to have the latest version of OF. Do you have any plans to update this addon to the latest OF commits? Thank you!

**Comment by frauzufall** [comment]
Sorry for missing this issue, I had some deadlines, and thanks for answering, @avilleret . If I understood your conversation correctly, the problem was the wrong OF version referenced in the README - I will fix that. Please tell me if there are other issues with the current OF master branch.

**Comment by narner** [comment]
No worries @frauzufall; I can confirm that the examples do build using the current OF master branch.

**Comment by LauraLaureus** [comment]
I have the same problem, I can  find de ofJSON, I have the latest version of OpenFrameworks 0.9.8 running on Win 10, has anyone build in this platform now?
