### ISSUE TITLE
Weird behavior in ofxGuiMatrix

### ISSUE THREAD

**Issue by gorkacortazar** [frauzufall/ofxGuiExtended#5]
Trying the matrix component, I noticed that in my case, the last row gets a weird behavior, omitting the last - 1 item and using the last one as the full column.

For example this is the data in one column:
![1_column](https://cloud.githubusercontent.com/assets/608719/8671619/06306266-2a27-11e5-858a-3bc975e53e3e.png)

And with two columns it miss one of the elements and the last one uses all the row:
![2_column](https://cloud.githubusercontent.com/assets/608719/8671637/344c1294-2a27-11e5-8955-7e38c1b99650.png)

**Comment by frauzufall** [comment]
Can you show me the code snippet you used to create the matrix? I can't reproduce it. Does the same thing happen when you change the column count in the addon example?

**Comment by gorkacortazar** [comment]
@frauzufall 

This code produces the effect (tested with the last master), where info is a ofxPanelExtended

```
drawTypeBooleans.push_back(ofParameter<bool>("none", true));
    drawTypeBooleans.push_back(ofParameter<bool>("area", false));
    drawTypeBooleans.push_back(ofParameter<bool>("line", false));
    drawTypeBooleans.push_back(ofParameter<bool>("fixture", false));
    drawTypeBooleans.push_back(ofParameter<bool>("pixel", false));
    drawTypeBooleans.push_back(ofParameter<bool>("all", false));
    info.add(drawTypeMatrix.setup("Draw Type", 2));
    for (int i = 0; i < drawTypeBooleans.size(); i++) {
        drawTypeMatrix.add(new ofxMinimalToggle(drawTypeBooleans.at(i)));
    }
    drawTypeMatrix.allowMultipleActiveToggles(false);
```

**Comment by frauzufall** [comment]
If you need a quick fix, you can do this:

```
drawTypeMatrix.setup("Draw Type", 2);
    for (int i = 0; i < drawTypeBooleans.size(); i++) {
        drawTypeMatrix.add(new ofxMinimalToggle(drawTypeBooleans.at(i)));
    }
info.add(&drawTypeMatrix);
```

But I will also look into this to determine why the order makes a difference here.

**Comment by frauzufall** [comment]
Alright, can you test again? It should work.

**Comment by gorkacortazar** [comment]
@frauzufall I juste tested it and its working properly, i tried a varied compbination of elements numbers and grid with combinations without any problem... thanks!
