### ISSUE TITLE
removing controls

### ISSUE THREAD

**Issue by andreirt** [frauzufall/ofxGuiExtended#52]
I am writing an application composed by several different sections. Each section has its own ofxGuiGroup, where the needed controls are placed. When a section is deleted, its container is removed by this code:

    this->container->parent()->removeChild(this->container);

Originally, this code was called in response to a button being pressed. But this caused a lot of problems, like some mouse events still being fired, and ofxGuiElement setValue() trying to acess ofParameters which point to variables that don't exist anymore. I tried some things, but the solution was:

- when the button to change the section is pressed, the container is hidden

`this->container->setHidden(true);`

- the section container is removed only after, when no events relative to its controls can be disptached

`this->container->parent()->removeChild(this->container);`

This design seems a bit strange for me. I guess there is some way to remove controls from screen, cleaning all references to them. Is there?

Thank you,
Andrei

**Comment by frauzufall** [comment]
Looks like a bug, thanks for reporting, will check it out!

**Comment by frauzufall** [comment]
Hey, I fixed missing event listener removals in the slider groups, maybe that was also the problem in your case. If you are still using this, can you please update and test again? Thanks!
