### ISSUE TITLE
Error building examples

### ISSUE THREAD

**Issue by narner** [frauzufall/ofxGuiExtended#53]
Hi there, 

It looks like I'm experiencing a similar problem as Issue #49. 

I'm using the most recent commit from the addon's Master branch, and I've tested on both the most recent OF master branch, and on OF 0.9.8.

On OF 0.9.8, I'm getting an `ofJson.h` file not found error in `ofxGuiElement.h`. On the most recent commit on the OF Master branch, I'm getting that error, as well as an error of `glm/glm.hpp` not found in `ofConstants.h` in Open Frameworks itself (which seems to be related to OF itself).

Thank you!

**Comment by frauzufall** [comment]
Hey, thanks for reporting the issue. I tried to reproduce it, but I can't, the travis-ci and appveyor test also built successfully, so I think it may be an issue with your OF installation.

In OF 0.9.8 ofJson.h is not included yet, that is correct, not sure why though, the file is in the repository since the beginning of March'16.. (https://github.com/openframeworks/openFrameworks/commit/9f3a4e472c47cc8275c2237a780d085f49077e12) 

In the current OF master branch, you should be able to locate ofJson here: `libs/openFrameworks/utils/ofJson.h`. Can you check whether this files exists in your OF installation?

**Comment by narner** [comment]
Ok, thanks for checking! Weird that Json.h isn't in OF 0.9.8 🤔 

On master, it does look like that file is there:

<img width="817" alt="screen shot 2017-05-09 at 8 56 29 am" src="https://cloud.githubusercontent.com/assets/2131591/25852202/95e05684-3496-11e7-876d-3a7e378af4bd.png">

But, being on the latest commit of the OF master branch introduces that `GL/glew.h` file not found error...trying to determine at which commit in the master branch where that doesn't occur...

**Comment by frauzufall** [comment]
Check the `scripts` folder of OF, a while ago a script called `download_libs.sh` was added.. Try running it.

**Comment by narner** [comment]
Yup, it looks like it was an issue with my OF install...I re-cloned the repo following the instructions in `INSTALL_FROM_GITHUB.MD`. When I tried to run that script you mentioned above, I kept getting errors (here's a [forum post I made](https://forum.openframeworks.cc/t/problem-running-download-libs-sh-on-mac/26742).

If you have a second to take a look, I'd be grateful!

**Comment by narner** [comment]
It actually ended up being that the script didn't run b/c I had a space in a folder that was part of my OF path. Now that that's fixed, I can build the examples for ofxGuiExtended just fine...totally my fault :) 

Thanks for the great addon!

**Comment by frauzufall** [comment]
Well that sounds like an issue of OF rather than your fault, but I am happy that it works now for you.

**Comment by moebiussurfing** [comment]
hey @narner ! it worked in 0.9.8? or it's github branch only?

**Comment by moebiussurfing** [comment]
didn't worked for me on OF github neither...

**Comment by alexdmiller** [comment]
Is there anyway to use ofxGuiExtended and 0.9.8? I don't even want the JSON features. It's frustrating that this library still depends on something that isn't in the official OF release.

**Comment by frauzufall** [comment]
This addon was built from the core gui addon and was initially meant to stay in the core. Therefore the dependency on something from the master branch that is not released yet. I don't have the time to make a version without JSON, sorry.
