### ISSUE TITLE
strange behaviour with a panel containing tabbed pages when recall settings of the parameters

### ISSUE THREAD

**Issue by Taprik** [frauzufall/ofxGuiExtended#55]
First : 
What a wonderfull addon. Thanks some much for that. This is an easy way to make nice UI with OF and really well built.

I've tried many of the examples with of_v20170517_vs_release on windows 10. Every thing is perfectly working.

I've found a strange behaviour when I mix some features : 
I've made a panel with tabbed pages. When I recall settings of every parameters of the tabbed pages they are correctly set but the pages seems to be selected one by one when the recall is performing and the content of every page does not appear. At the end of the recall, the last page seems to be selected but the content of the lastly selected pages is displayed. When I try to select the last page to display its content I can't, I have to select an other page (not the last one), and then the behaviour returns to normal.
Here is the code I use.
----------------- ofApp.h -----------------------------------------
#pragma once

#include "ofMain.h"
#include "ofxGuiExtended.h"

class ofApp : public ofBaseApp {

	public:
		void setup();
		void update();
		void draw();

		void exit();

		void keyPressed(int key);
		void keyReleased(int key);
		void mouseMoved(ofMouseEventArgs & args);
		void mouseDragged(ofMouseEventArgs & args);
		void mousePressed(ofMouseEventArgs & args);
		void mouseReleased(ofMouseEventArgs & args);
		void windowResized(int w, int h);
		void dragEvent(ofDragInfo dragInfo);
		void gotMessage(ofMessage msg);

	private:

		ofxGui gui;
		ofxGuiPanel* panel;

		ofParameter<float> param1;
		ofParameter<float> param2;

		ofParameter<float> param3;
		ofParameter<float> param4;
};

--------------------------------------------------------------------------------
---------------------------- ofApp.cpp ----------------------------------------
#include "ofApp.h"

//--------------------------------------------------------------
void ofApp::setup(){

	ofSetFrameRate(120);

	ofSetLogLevel(OF_LOG_VERBOSE);

	ofxGuiGroup* all = gui.addGroup("all", ofJson({
		{"position", "static"},
		{"height", "600"},
		{"width", "600"},
		{"show-header", false},
		{"background-color", "#000000"}
	}));

	// add header group
	panel = all->addPanel("header", ofJson({
		{"flex-direction", "row"},
		{"show-header", true},
		{"height", 50},
		{"background-color", "#F40056"}
	}));
	panel->addLabel("this is the panel");

	// create tab container
	ofxGuiTabs* tabbed_pages = panel->addTabs("tabbedpages", ofJson());

	// add a page to the tab container
	ofxGuiGroup* page1 = tabbed_pages->addGroup("page1", ofJson({
		{"background-color", "#2377BA"},
		{"padding", 10},
	}));

	// add labels with random width to the first page
	for(int i = 0; i < 33; i++){
		page1->addLabel(ofToString(i), ofJson({
			{"border-width", 1},
			{"width", ofRandom(30, 130)}
		}));
	}

	// add two more pages 

	param1.set("param1", 0.5, 0, 1);
	param2.set("param2", 0.5, 0, 1);
	

	ofxGuiGroup* page2  = tabbed_pages->addGroup("page2", ofJson({{"background-color", "#00CA98"}}));

	page2->add(param1);
	page2->add(param2);
	
	param3.set("param3", 0.5, 0, 1);
	param4.set("param4", 0.5, 0, 1);

	ofxGuiGroup* page3 = tabbed_pages->addGroup("page3", ofJson({{"background-color", "#ffaa00"}}));

	page3->add(param3);
	page3->add(param4);

}

//--------------------------------------------------------------
void ofApp::exit(){
}

//--------------------------------------------------------------
void ofApp::update(){
}

//--------------------------------------------------------------
void ofApp::draw(){

	ofBackgroundGradient(ofColor::white, ofColor::gray);

}

//--------------------------------------------------------------
void ofApp::keyPressed(int key){
}

//--------------------------------------------------------------
void ofApp::keyReleased(int key){
	switch(key){
	 case 'f': {
		 ofToggleFullscreen();
		 break;
	 }
	 case 'r':
		 panel->loadFromFile("settings.xml");
		 break;
	 default:
		 break;
	}

}

//--------------------------------------------------------------
void ofApp::mouseMoved(ofMouseEventArgs & args){

}

//--------------------------------------------------------------
void ofApp::mouseDragged(ofMouseEventArgs & args){
}

//--------------------------------------------------------------
void ofApp::mousePressed(ofMouseEventArgs & args){
}

//--------------------------------------------------------------
void ofApp::mouseReleased(ofMouseEventArgs & args){
}

//--------------------------------------------------------------
void ofApp::windowResized(int w, int h){
}

//--------------------------------------------------------------
void ofApp::gotMessage(ofMessage msg){

}

//--------------------------------------------------------------
void ofApp::dragEvent(ofDragInfo dragInfo){

}
------------------------------------------------------------------------

**Comment by Taprik** [comment]
A workaround is to call gateActiveTabIndex before and setActiveTab after.

         int j = tabbed_pages->getActiveTabIndex();
			panel->loadFromFile("settings.xml");
			tabbed_pages->setActiveTab(j);

Cheers

**Comment by frauzufall** [comment]
Hey, sorry for my late reply! Thanks for reporting this issue and providing the code, made it easy to understand your problem and to (hopefully) fix it. Please update the addon and tell me if it is still not working.
