### ISSUE TITLE
compilation issues on windows

### ISSUE THREAD

**Issue by maybites** [frauzufall/ofxGuiExtended#58]
Hi

I am currently struggling compiling examples on windows 10 with the following error messages:

1>------ Build started: Project: openframeworksLib, Configuration: Debug Win32 ------
1>  openframeworksLib.vcxproj -> C:\Users\maybites\Arbeiten\02_code\openFrameworks\of\libs\openFrameworksCompiled\project\vs\..\..\lib\vs\Win32\openframeworksLib_debug.lib
2>------ Build started: Project: examplePanel, Configuration: Debug Win32 ------
2>  main.cpp
2>  ofApp.cpp
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\Types.h(213): warning C4521: 'DOM::Any': multiple copy constructors specified (compiling source file src\ofApp.cpp)
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\Types.h(213): warning C4521: 'DOM::Any': multiple copy constructors specified (compiling source file src\main.cpp)
2>  ofxGuiContainer.cpp
2>  ofxGuiGroup.cpp
2>  ofxGuiMenu.cpp
2>  ofxGuiPanel.cpp
2>  ofxGuiSliderGroup.cpp
2>  ofxGuiTabs.cpp
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\Types.h(88): error C2061: syntax error: identifier 'decay' (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiTabs.cpp)
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\Types.h(94): error C2631: 'Any': a class or enum cannot be defined in an alias template (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiTabs.cpp)
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\Events.h(38): error C2143: syntax error: missing ';' before '{' (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiTabs.cpp)
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\Events.h(38): error C2447: '{': missing function header (old-style formal list?) (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiTabs.cpp)
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\EventTarget.h(45): error C2631: 'EventTarget': a class or enum cannot be defined in an alias template (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiTabs.cpp)
2>..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiTabs.cpp : fatal error C1903: unable to recover from previous error(s); stopping compilation
2>  INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe'
2>      Please choose the Technical Support command on the Visual C++
2>      Help menu, or open the Technical Support help file for more information
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\Types.h(88): error C2061: syntax error: identifier 'decay' (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiMenu.cpp)
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\Types.h(94): error C2631: 'Any': a class or enum cannot be defined in an alias template (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiMenu.cpp)
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\Events.h(38): error C2143: syntax error: missing ';' before '{' (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiMenu.cpp)
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\Events.h(38): error C2447: '{': missing function header (old-style formal list?) (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiMenu.cpp)
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\EventTarget.h(45): error C2631: 'EventTarget': a class or enum cannot be defined in an alias template (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiMenu.cpp)
2>..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiMenu.cpp : fatal error C1903: unable to recover from previous error(s); stopping compilation
2>  INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe'
2>      Please choose the Technical Support command on the Visual C++
2>      Help menu, or open the Technical Support help file for more information
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\Types.h(88): error C2061: syntax error: identifier 'decay' (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiSliderGroup.cpp)
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\Types.h(94): error C2631: 'Any': a class or enum cannot be defined in an alias template (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiSliderGroup.cpp)
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\Events.h(38): error C2143: syntax error: missing ';' before '{' (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiSliderGroup.cpp)
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\Events.h(38): error C2447: '{': missing function header (old-style formal list?) (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiSliderGroup.cpp)
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\EventTarget.h(45): error C2631: 'EventTarget': a class or enum cannot be defined in an alias template (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiSliderGroup.cpp)
2>..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiSliderGroup.cpp : fatal error C1903: unable to recover from previous error(s); stopping compilation
2>  INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe'
2>      Please choose the Technical Support command on the Visual C++
2>      Help menu, or open the Technical Support help file for more information
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\Types.h(88): error C2061: syntax error: identifier 'decay' (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiGroup.cpp)
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\Types.h(94): error C2631: 'Any': a class or enum cannot be defined in an alias template (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiGroup.cpp)
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\Events.h(38): error C2143: syntax error: missing ';' before '{' (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiGroup.cpp)
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\Events.h(38): error C2447: '{': missing function header (old-style formal list?) (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiGroup.cpp)
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\EventTarget.h(45): error C2631: 'EventTarget': a class or enum cannot be defined in an alias template (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiGroup.cpp)
2>..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiGroup.cpp : fatal error C1903: unable to recover from previous error(s); stopping compilation
2>  INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe'
2>      Please choose the Technical Support command on the Visual C++
2>      Help menu, or open the Technical Support help file for more information
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\Types.h(88): error C2061: syntax error: identifier 'decay' (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiContainer.cpp)
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\Types.h(94): error C2631: 'Any': a class or enum cannot be defined in an alias template (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiContainer.cpp)
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\Events.h(38): error C2143: syntax error: missing ';' before '{' (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiContainer.cpp)
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\Events.h(38): error C2447: '{': missing function header (old-style formal list?) (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiContainer.cpp)
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\EventTarget.h(45): error C2631: 'EventTarget': a class or enum cannot be defined in an alias template (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiContainer.cpp)
2>..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiContainer.cpp : fatal error C1903: unable to recover from previous error(s); stopping compilation
2>  INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe'
2>      Please choose the Technical Support command on the Visual C++
2>      Help menu, or open the Technical Support help file for more information
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\Types.h(88): error C2061: syntax error: identifier 'decay' (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiPanel.cpp)
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\Types.h(94): error C2631: 'Any': a class or enum cannot be defined in an alias template (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiPanel.cpp)
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\Events.h(38): error C2143: syntax error: missing ';' before '{' (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiPanel.cpp)
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\Events.h(38): error C2447: '{': missing function header (old-style formal list?) (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiPanel.cpp)
2>c:\users\maybites\arbeiten\02_code\openframeworks\of\addons\ofxguiextended\src\dom\EventTarget.h(45): error C2631: 'EventTarget': a class or enum cannot be defined in an alias template (compiling source file ..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiPanel.cpp)
2>..\..\..\addons\ofxGuiExtended\src\containers\ofxGuiPanel.cpp : fatal error C1903: unable to recover from previous error(s); stopping compilation
2>  INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe'
2>      Please choose the Technical Support command on the Visual C++
2>      Help menu, or open the Technical Support help file for more information
2>cl : Command line error D8040: error creating or communicating with child process
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

any ideas why this happens?

**Comment by frauzufall** [comment]
Hey @maybites, sorry for the late reply. There were some references to the namespace `std` missing, it should work now.
