### ISSUE TITLE
Exception thrown at exit in windows (VS2015)

### ISSUE THREAD

**Issue by gorkacortazar** [frauzufall/ofxGuiExtended#6]
When you close the applciation, you get a long list of exceptions in this fashion

```
Exception thrown at 0x00007FF931D38B9C in pixelTesterV2.exe: Microsoft C++ exception: ofEventAttendedException at memory location 0x000000000013F8D8.
```

May be related to listeners not cleaned on destruction, I'll research a little bit more about this.

**Comment by frauzufall** [comment]
I don't get any exceptions, but I found one missing unregisterMouseEvents(). Can you please test again?

**Comment by gorkacortazar** [comment]
Its confirmed that in the last version this exception is not thrown anymore.

**Comment by frauzufall** [comment]
awesome.
