### ISSUE TITLE
problem compiling examples

### ISSUE THREAD

**Issue by martialgallorini** [frauzufall/ofxGuiExtended#7]
I downloaded the source and gave it a try. I was unable to build the examples. Compiler throws the following error : 

.../ofxGuiExtended/src/ofxCanvas.cpp:23:5: Use of undeclared identifier 'setNeedsRedraw'

**Comment by frauzufall** [comment]
Thanks for trying! That's strange. It works for me and the function is part of the inherited class `ofxBaseGui`. Is your repository up to date? I had not pushed all commits to github when I wrote the blog post.

**Comment by martialgallorini** [comment]
note : i am using oF 0.8.4 under OSX Yosemite and Xcode 6.1.1
i just grabbed the latest source from github
I think you may use a different version (like the latest 0.9) as some functions seems deprecated

**Comment by frauzufall** [comment]
That's it. I use the current git version of OF. This also means I can't do anything about it, I'm sorry. I will include a note about this in the readme.

**Comment by martialgallorini** [comment]
Yes. There are also some deprecated functions like 

img.loadImage() in oF 084 instead of img.load() in oF 09

ofRect() in oF 084 instead of ofDrawRectangle() in oF 09

and so on...

I just tried, and it is ok with oF 0.9 nightly

thanks
